"""Workbench/Mechanical batch helpers for fresh-project exact probe export."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys

from . import config
from .csv_format import FACE_ORDER
from .mechdb_cache import export_cached_probe_csvs


NUMBER_RE = re.compile(r"[-+]?(?:(?:\d+\.\d*)|(?:\.\d+)|(?:\d+))(?:[EeDd][-+]?\d+)?")
PROBE_FILE_RE = re.compile(r"Face_Accel_Probe_(\d+)\.(?:txt|csv)$", re.I)


@dataclass(frozen=True)
class MechanicalBatchConfig:
    case: str
    project_path: Path
    rst_path: Path
    output_dir: Path
    probe_text_dir: Path
    status_path: Path
    mechanical_script_path: Path
    workbench_system: str = config.HPC_SYSTEM
    workbench_component: str = config.HPC_WORKBENCH_COMPONENT


def find_runwb2(explicit: str | Path | None, env: dict[str, str] | None = None) -> Path:
    """Find the Workbench batch launcher."""
    current_env = os.environ if env is None else env
    candidates: list[Path] = []
    if explicit:
        candidates.append(Path(explicit))

    env_value = current_env.get(config.HPC_RUNWB2_ENV_VAR)
    if env_value:
        candidates.append(Path(env_value))

    which = shutil.which("runwb2", path=current_env.get("PATH"))
    if which:
        candidates.append(Path(which))

    for name, value in sorted(current_env.items()):
        if not name.startswith("AWP_ROOT"):
            continue
        root = Path(value)
        candidates.extend(
            [
                root / "Framework" / "bin" / "Linux64" / "runwb2",
                root / "Framework" / "bin" / "Win64" / "runwb2.exe",
            ]
        )

    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(2, "No such file or directory", str(candidates[0] if candidates else "runwb2"))


def build_workbench_journal(batch_config: MechanicalBatchConfig) -> str:
    """Build a Workbench journal that opens the project and runs Mechanical Python."""
    return f'''# Workbench journal generated by RST2CSVAutomation.
PROJECT_PATH = r"{_path(batch_config.project_path)}"
MECHANICAL_SCRIPT_PATH = r"{_path(batch_config.mechanical_script_path)}"
SYSTEM_NAME = "{batch_config.workbench_system}"
COMPONENT_NAME = "{batch_config.workbench_component}"

Open(FilePath=PROJECT_PATH)
system = GetSystem(Name=SYSTEM_NAME)
container = system.GetContainer(ComponentName=COMPONENT_NAME)
container.Edit(Hidden=True)

script_stream = open(MECHANICAL_SCRIPT_PATH, "r")
try:
    mechanical_command = script_stream.read()
finally:
    script_stream.close()

container.SendCommand(Language="Python", Command=mechanical_command)
Save(Overwrite=True)
'''


def build_mechanical_export_script(batch_config: MechanicalBatchConfig) -> str:
    """Build a Mechanical Python script that exports all ResultProbe time histories."""
    return f'''# Mechanical Python script generated by RST2CSVAutomation.
# Compatible with IronPython syntax used by Mechanical.
CASE_NAME = r"{batch_config.case}"
RST_PATH = r"{_path(batch_config.rst_path)}"
PROBE_TEXT_DIR = r"{_path(batch_config.probe_text_dir)}"
STATUS_PATH = r"{_path(batch_config.status_path)}"
RESULT_PREFIX = "Face_Accel_Probe_"
EXPECTED_PROBE_COUNT = 700

import os
import re
import traceback


def _write_status(status, message):
    parent = os.path.dirname(STATUS_PATH)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    stream = open(STATUS_PATH, "w")
    try:
        stream.write(status + "\\n")
        stream.write(message + "\\n")
    finally:
        stream.close()


def _children(obj):
    try:
        return list(obj.Children)
    except Exception:
        return []


def _collect_probes(root, probes):
    name = ""
    try:
        name = root.Name
    except Exception:
        pass
    if name.startswith(RESULT_PREFIX):
        probes.append(root)
    for child in _children(root):
        _collect_probes(child, probes)


def _probe_number(probe):
    return int(probe.Name.rsplit("_", 1)[1])


def _ensure_result_link(analysis):
    try:
        work_dir = analysis.WorkingDir
    except Exception:
        return
    if not work_dir:
        return
    target = os.path.join(work_dir, "file.rst")
    if os.path.exists(target):
        return
    if not os.path.isdir(work_dir):
        os.makedirs(work_dir)
    try:
        os.symlink(RST_PATH, target)
    except Exception:
        # Some systems disable symlinks; fall back to a lightweight shell ln on Linux.
        try:
            import subprocess
            subprocess.call(["ln", "-s", RST_PATH, target])
        except Exception:
            pass


def _try_set_result_path(obj):
    for attr in ("ResultFilePath", "ResultFileName"):
        try:
            setattr(obj, attr, RST_PATH)
        except Exception:
            pass
    for method_name in ("SetResultFilePath", "SetResultFile"):
        try:
            method = getattr(obj, method_name)
            method(RST_PATH)
        except Exception:
            pass


try:
    if not os.path.isdir(PROBE_TEXT_DIR):
        os.makedirs(PROBE_TEXT_DIR)

    analyses = list(ExtAPI.DataModel.AnalysisList)
    if not analyses:
        raise Exception("No Mechanical analysis found in the project.")
    analysis = analyses[0]
    _ensure_result_link(analysis)
    _try_set_result_path(analysis)

    solution = analysis.Solution
    _try_set_result_path(solution)
    probes = []
    _collect_probes(solution, probes)
    probes = sorted(probes, key=_probe_number)
    if len(probes) != EXPECTED_PROBE_COUNT:
        raise Exception("Expected 700 Face_Accel_Probe results, found " + str(len(probes)))

    try:
        solution.EvaluateAllResults()
    except Exception:
        pass

    for probe in probes:
        try:
            probe.EvaluateAllResults()
        except Exception:
            pass
        out_path = os.path.join(PROBE_TEXT_DIR, probe.Name + ".txt")
        probe.ExportToTextFile(out_path)

    _write_status("OK", "Exported " + str(len(probes)) + " probe text files for " + CASE_NAME)
except Exception:
    _write_status("ERROR", traceback.format_exc())
    raise
'''


def write_mechanical_batch_files(
    batch_config: MechanicalBatchConfig,
    workbench_journal_path: str | Path,
) -> tuple[Path, Path]:
    """Write Mechanical Python and Workbench journal files."""
    batch_config.mechanical_script_path.parent.mkdir(parents=True, exist_ok=True)
    batch_config.mechanical_script_path.write_text(
        build_mechanical_export_script(batch_config),
        encoding="utf-8",
        newline="\n",
    )
    journal_path = Path(workbench_journal_path)
    journal_path.parent.mkdir(parents=True, exist_ok=True)
    journal_path.write_text(
        build_workbench_journal(batch_config),
        encoding="utf-8",
        newline="\n",
    )
    return batch_config.mechanical_script_path, journal_path


def run_workbench_batch(
    runwb2_path: str | Path,
    journal_path: str | Path,
    log_dir: str | Path,
) -> subprocess.CompletedProcess:
    """Run Workbench in batch mode and capture logs."""
    log_path = Path(log_dir)
    log_path.mkdir(parents=True, exist_ok=True)
    command = [str(runwb2_path), "-B", "-R", str(journal_path)]
    completed = subprocess.run(command, text=True, capture_output=True)
    (log_path / "workbench_stdout.log").write_text(completed.stdout or "", encoding="utf-8", errors="replace")
    (log_path / "workbench_stderr.log").write_text(completed.stderr or "", encoding="utf-8", errors="replace")
    if completed.returncode != 0:
        raise RuntimeError("Workbench batch failed with exit code {}".format(completed.returncode))
    return completed


def parse_probe_export_text(
    path: str | Path,
    result_sets: list[tuple[int, float]],
) -> tuple[float, ...]:
    """Parse one Mechanical `ExportToTextFile` probe history."""
    text = _read_text(Path(path))
    line_numbers = [_numbers_from_line(line) for line in text.splitlines()]
    matched: list[float] = []
    search_start = 0
    for _step, time_value in result_sets:
        found = False
        for index in range(search_start, len(line_numbers)):
            numbers = line_numbers[index]
            if len(numbers) < 2:
                continue
            match_index = _matching_time_index(numbers, time_value)
            if match_index is None:
                continue
            value_candidates = numbers[match_index + 1 :]
            matched.append(float(value_candidates[-1] if value_candidates else numbers[-1]))
            search_start = index + 1
            found = True
            break
        if not found:
            break

    if len(matched) == len(result_sets):
        return tuple(matched)

    fallback = [numbers[-1] for numbers in line_numbers if len(numbers) >= 2]
    if len(fallback) == len(result_sets):
        return tuple(float(value) for value in fallback)

    raise ValueError(
        "could not parse {} values from {}; parsed {}".format(
            len(result_sets),
            path,
            len(matched) or len(fallback),
        )
    )


def combine_probe_text_exports(
    probe_text_dir: str | Path,
    result_sets: list[tuple[int, float]],
    output_dir: str | Path,
    faces: tuple[str, ...] = FACE_ORDER,
) -> list[Path]:
    """Combine per-probe Mechanical text exports into FaceAccel CSV files."""
    histories: dict[int, tuple[float, ...]] = {}
    for probe_path in Path(probe_text_dir).iterdir():
        match = PROBE_FILE_RE.match(probe_path.name)
        if not match:
            continue
        probe_number = int(match.group(1))
        histories[probe_number] = parse_probe_export_text(probe_path, result_sets)
    return export_cached_probe_csvs(histories, result_sets, output_dir, faces=faces)


def _read_text(path: Path) -> str:
    raw = path.read_bytes()
    for encoding in ("utf-8-sig", "utf-16", "gb2312", sys.getdefaultencoding()):
        try:
            return raw.decode(encoding)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", errors="replace")


def _numbers_from_line(line: str) -> list[float]:
    values: list[float] = []
    for match in NUMBER_RE.finditer(line):
        try:
            values.append(float(match.group(0).replace("D", "E").replace("d", "e")))
        except ValueError:
            continue
    return values


def _matching_time_index(numbers: list[float], expected_time: float) -> int | None:
    tolerance = max(1e-8, abs(expected_time) * 1e-7)
    matches = [index for index, value in enumerate(numbers[:-1]) if abs(value - expected_time) <= tolerance]
    if not matches:
        return None
    return matches[-1]


def _path(path: Path) -> str:
    return str(path).replace("\\", "/")
