"""Workbench/Mechanical batch helpers for fresh-project exact probe export."""

from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import shutil
import subprocess

from . import config


@dataclass(frozen=True)
class MechanicalBatchConfig:
    case: str
    project_path: Path
    rst_path: Path
    output_dir: Path
    status_path: Path
    mechanical_script_path: Path
    workbench_system: str = config.HPC_SYSTEM
    workbench_component: str = config.HPC_WORKBENCH_COMPONENT


def find_runwb2(explicit: str | Path | None, env: dict[str, str] | None = None) -> Path:
    """Find the Workbench batch launcher."""
    current_env = os.environ if env is None else env
    candidates: list[Path] = []
    if explicit:
        candidates.append(Path(explicit))

    env_value = current_env.get(config.HPC_RUNWB2_ENV_VAR)
    if env_value:
        candidates.append(Path(env_value))

    which = shutil.which("runwb2", path=current_env.get("PATH"))
    if which:
        candidates.append(Path(which))

    for name, value in sorted(current_env.items()):
        if not name.startswith("AWP_ROOT"):
            continue
        root = Path(value)
        candidates.extend(
            [
                root / "Framework" / "bin" / "Linux64" / "runwb2",
                root / "Framework" / "bin" / "Win64" / "runwb2.exe",
            ]
        )

    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(2, "No such file or directory", str(candidates[0] if candidates else "runwb2"))


def build_workbench_journal(batch_config: MechanicalBatchConfig) -> str:
    """Build a Workbench journal that opens the project and runs Mechanical Python."""
    return f'''# Workbench journal generated by RST2CSVAutomation.
PROJECT_PATH = r"{_path(batch_config.project_path)}"
MECHANICAL_SCRIPT_PATH = r"{_path(batch_config.mechanical_script_path)}"
SYSTEM_NAME = "{batch_config.workbench_system}"
COMPONENT_NAME = "{batch_config.workbench_component}"

Open(FilePath=PROJECT_PATH)
system = GetSystem(Name=SYSTEM_NAME)
container = system.GetContainer(ComponentName=COMPONENT_NAME)
container.Edit(Hidden=True)

script_stream = open(MECHANICAL_SCRIPT_PATH, "r")
try:
    mechanical_command = script_stream.read()
finally:
    script_stream.close()

container.SendCommand(Language="Python", Command=mechanical_command)
Save(Overwrite=True)
'''


def build_mechanical_export_script(batch_config: MechanicalBatchConfig) -> str:
    """Build a Mechanical Python script that populates exact cached probe histories."""
    return f'''# Mechanical Python script generated by RST2CSVAutomation.
# Compatible with IronPython syntax used by Mechanical.
CASE_NAME = r"{batch_config.case}"
RST_PATH = r"{_path(batch_config.rst_path)}"
STATUS_PATH = r"{_path(batch_config.status_path)}"
RESULT_PREFIX = "Face_Accel_Probe_"
EXPECTED_PROBE_COUNT = 700

import os
import subprocess
import traceback


def _write_status(status, message):
    parent = os.path.dirname(STATUS_PATH)
    if parent and not os.path.isdir(parent):
        os.makedirs(parent)
    stream = open(STATUS_PATH, "w")
    try:
        stream.write(status + "\\n")
        stream.write(message + "\\n")
    finally:
        stream.close()


def _children(obj):
    try:
        return list(obj.Children)
    except Exception:
        return []


def _collect_probes(root, probes):
    name = ""
    try:
        name = root.Name
    except Exception:
        pass
    if name.startswith(RESULT_PREFIX):
        probes.append(root)
    for child in _children(root):
        _collect_probes(child, probes)


def _probe_number(probe):
    return int(probe.Name.rsplit("_", 1)[1])


def _native_path(path):
    if os.name == "nt":
        return path.replace("/", "\\\\")
    return path


def _ensure_result_link(analysis):
    try:
        work_dir = analysis.WorkingDir
    except Exception:
        raise Exception("Mechanical analysis has no WorkingDir; cannot attach RST file.")
    if not work_dir:
        raise Exception("Mechanical analysis WorkingDir is empty; cannot attach RST file.")
    target = os.path.join(work_dir, "file.rst")
    if os.path.exists(target):
        return target
    if not os.path.isdir(work_dir):
        os.makedirs(work_dir)
    try:
        lexists = os.path.lexists
    except Exception:
        lexists = os.path.exists
    try:
        if lexists(target):
            os.remove(target)
    except Exception:
        pass

    link_source = _native_path(RST_PATH)
    errors = []
    try:
        os.symlink(link_source, target)
    except Exception as exc:
        errors.append("os.symlink: " + str(exc))
    if not os.path.exists(target):
        if os.name == "nt":
            command = ["cmd", "/c", "mklink", target, link_source]
        else:
            command = ["ln", "-s", link_source, target]
        try:
            exit_code = subprocess.call(command)
            if exit_code != 0:
                errors.append(" ".join(command) + " exited " + str(exit_code))
        except Exception as exc:
            errors.append(" ".join(command) + ": " + str(exc))
    if not os.path.exists(target):
        raise Exception(
            "Result link was not created: target=" + target
            + ", rst=" + RST_PATH
            + ", errors=" + "; ".join(errors)
        )
    return target


def _try_set_result_path(obj):
    for attr in ("ResultFilePath", "ResultFileName"):
        try:
            setattr(obj, attr, RST_PATH)
        except Exception:
            pass
    for method_name in ("SetResultFilePath", "SetResultFile"):
        try:
            method = getattr(obj, method_name)
            method(RST_PATH)
        except Exception:
            pass


def _point_count(probe):
    try:
        return int(probe.InternalObject.numPoints)
    except Exception:
        return 0


def _empty_probes(probes):
    empty = []
    for probe in probes:
        if _point_count(probe) <= 0:
            empty.append(probe)
    return empty


try:
    analyses = list(ExtAPI.DataModel.AnalysisList)
    if not analyses:
        raise Exception("No Mechanical analysis found in the project.")
    analysis = analyses[0]
    result_link = _ensure_result_link(analysis)
    _try_set_result_path(analysis)

    solution = analysis.Solution
    _try_set_result_path(solution)
    probes = []
    _collect_probes(solution, probes)
    probes = sorted(probes, key=_probe_number)
    if len(probes) != EXPECTED_PROBE_COUNT:
        raise Exception("Expected 700 Face_Accel_Probe results, found " + str(len(probes)))

    try:
        solution.EvaluateAllResults()
    except Exception as exc:
        raise Exception("Solution.EvaluateAllResults failed after attaching " + result_link + ": " + str(exc))

    empty_probes = _empty_probes(probes)
    for probe in empty_probes:
        try:
            probe.EvaluateAllResults()
        except Exception:
            pass
        try:
            probe.RetrieveResult()
        except Exception:
            pass
    empty_probes = _empty_probes(probes)

    if empty_probes:
        raise Exception(
            "Cached histories were not generated for "
            + str(len(empty_probes))
            + " probes; first missing probes: "
            + ", ".join([probe.Name for probe in empty_probes[:10]])
        )

    _write_status("OK", "Cached histories generated for " + str(len(probes)) + " probes for " + CASE_NAME)
except Exception:
    _write_status("ERROR", traceback.format_exc())
    raise
'''


def write_mechanical_batch_files(
    batch_config: MechanicalBatchConfig,
    workbench_journal_path: str | Path,
) -> tuple[Path, Path]:
    """Write Mechanical Python and Workbench journal files."""
    batch_config.mechanical_script_path.parent.mkdir(parents=True, exist_ok=True)
    batch_config.mechanical_script_path.write_text(
        build_mechanical_export_script(batch_config),
        encoding="utf-8",
        newline="\n",
    )
    journal_path = Path(workbench_journal_path)
    journal_path.parent.mkdir(parents=True, exist_ok=True)
    journal_path.write_text(
        build_workbench_journal(batch_config),
        encoding="utf-8",
        newline="\n",
    )
    return batch_config.mechanical_script_path, journal_path


def run_workbench_batch(
    runwb2_path: str | Path,
    journal_path: str | Path,
    log_dir: str | Path,
) -> subprocess.CompletedProcess:
    """Run Workbench in batch mode and capture logs."""
    log_path = Path(log_dir)
    log_path.mkdir(parents=True, exist_ok=True)
    command = [str(runwb2_path), "-B", "-R", str(journal_path)]
    completed = subprocess.run(command, text=True, capture_output=True)
    (log_path / "workbench_stdout.log").write_text(completed.stdout or "", encoding="utf-8", errors="replace")
    (log_path / "workbench_stderr.log").write_text(completed.stderr or "", encoding="utf-8", errors="replace")
    if completed.returncode != 0:
        raise RuntimeError("Workbench batch failed with exit code {}".format(completed.returncode))
    return completed


def _path(path: Path) -> str:
    return str(path).replace("\\", "/")
